name: example
description: Automatically generates immutable data classes based on a "blueprint" mixin.
version: 0.0.1
author: Stefan Wehr (wehr@cp-med.com)
homepage: https://github.com/factisresearch/sum_data_types

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  quiver: '>=2.0.0 <3.0.0'
  pedantic: ^1.8.0
  kt_dart: ^0.7.0+1
  sum_data_types:
    git:
      url: https://github.com/factisresearch/sum_data_types
      path: sum_data_types
      ref: 518fd7a037eaebd9442c5202faec7b81c72ce717

dev_dependencies:
  build_runner: ^1.7.1
  sum_data_types_generator:
    path: ../sum_data_types_generator
  test: ^1.9.0
