name: example
description: Automatically generates immutable data classes based on a "blueprint" mixin.
version: 0.0.1
author: Stefan Wehr (wehr@cp-med.com)
homepage: https://github.com/factisresearch/sum_data_types

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  quiver: '>=2.0.0 <3.0.0'
  kt_dart: ^0.6.2
  sum_data_types:
    git:
      url: https://github.com/factisresearch/sum_data_types
      path: sum_data_types
      ref: bc4f9b9c61cf0b09c77f9000d6b9136a5322c1f6

dev_dependencies:
  build_runner: ^1.7.1
  sum_data_types_generator:
    path: ../sum_data_types_generator
  test: ^1.9.0
