name: example
description: Automatically generates immutable data classes based on a "blueprint" mixin.
version: 0.0.1
homepage: https://github.com/factisresearch/sum_data_types

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  quiver: ^3.0.1
  pedantic: ^1.8.0
  kt_dart: ^0.9.0
  sum_data_types: ^0.1.0

dev_dependencies:
  build_runner: ^1.7.1
  sum_data_types_generator:
    path: ../sum_data_types_generator
  test: ^1.9.0
