name: example
description: Automatically generates immutable data classes for you based on a mutable "blueprint" class.
version: 1.0.0
author: Marcel Garus <marcel.garus@gmail.com>
homepage: https://github.com/marcelgarus/flutter_data_classes

dependencies:
  quiver: '>=2.0.0 <3.0.0'
  kt_dart: ^0.6.2
  data_classes:
    path: ../data_classes

dev_dependencies:
  build_runner: ^1.0.0
  data_classes_generator:
    path: ../data_classes_generator
  test: ^1.5.1
