include: package:lints/recommended.yaml

linter:
  rules:
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unused_constructor_parameters: true
    await_only_futures: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_constructor_bodies: true
    empty_statements: true
    hash_and_equals: true
    implementation_imports: true
    library_names: true
    non_constant_identifier_names: true
    only_throw_errors: true
    package_api_docs: true
    package_names: true
    package_prefixed_library_names: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    slash_for_doc_comments: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_getters_setters: true
    unnecessary_statements: true
    unnecessary_this: false
    omit_local_variable_types: false

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
