name: sum_data_types
description: Automatically generates immutable data classes based on a "blueprint" mixin.
version: 0.1.1
homepage: https://github.com/factisresearch/sum_data_types

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.1.7

dev_dependencies:
  lints: ^2.1.0
