name: sum_data_types_generator
description: Automatically generates immutable data classes based on a "blueprint" mixin.
version: 0.0.1
author: Stefan Wehr (wehr@cp-med.com)
homepage: https://github.com/factisresearch/sum_data_types

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  analyzer: ^0.39.1
  pedantic: ^1.8.0
  build: ^1.2.0
  # sum_data_types: ^0.0.1
  sum_data_types:
    git:
      url: https://github.com/factisresearch/sum_data_types
      path: sum_data_types
      ref: a45f1a95fabb5ff27da3fad149af018aad00ba8a
  source_gen: ^0.9.0

dev_dependencies:
  build_runner: ^1.7.1
