name: sum_data_types_generator
description: Automatically generates immutable data classes based on a "blueprint" mixin.
version: 0.0.1
author: Stefan Wehr (wehr@cp-med.com)
homepage: https://github.com/factisresearch/sum_data_types

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  analyzer: ^0.36.0
  pedantic: ^1.8.0
  build: ^1.2.0
  # sum_data_types: ^0.0.1
  sum_data_types:
    git:
      url: https://github.com/factisresearch/sum_data_types
      path: sum_data_types
      ref: 518fd7a037eaebd9442c5202faec7b81c72ce717
  source_gen: ^0.9.0

dev_dependencies:
  build_runner: ^1.7.1
