name: sum_data_types_generator
description: Automatically generates immutable data classes based on a "blueprint" mixin.
version: 0.1.0
homepage: https://github.com/factisresearch/sum_data_types

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.3.0
  pedantic: ^1.8.0
  build: ^2.0.0
  sum_data_types: ^0.1.1
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^1.12.2
