name: sum_data_types_generator
description: Automatically generates immutable data classes based on a "blueprint" mixin.
version: 0.2.0
repository: https://github.com/factisresearch/sum_data_types/tree/master/sum_data_types_generator

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  analyzer: ^5.13.0
  build: ^2.0.0
  meta: ^1.1.7
  sum_data_types: ^0.1.1
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.7
  lints: ^2.1.0
  quiver: ^3.0.1
  kt_dart: ^1.1.0
  test: ^1.9.0
