name: sum_data_types_generator
description: Automatically generates immutable data classes based on a "blueprint" mixin.
version: 0.0.1
author: Stefan Wehr (wehr@cp-med.com)
homepage: https://github.com/factisresearch/sum_data_types

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  analyzer: ">=0.39.8 <0.41.0"
  pedantic: ^1.8.0
  build: ^1.2.2
  # sum_data_types: ^0.0.1
  sum_data_types:
    git:
      url: https://github.com/factisresearch/sum_data_types
      path: sum_data_types
      ref: 518fd7a037eaebd9442c5202faec7b81c72ce717
  source_gen: ^0.9.5

dev_dependencies:
  build_runner: ">= 1.9.0 <1.11.0"
