name: sum_data_types_generator
description: Automatically generates immutable data classes based on a "blueprint" mixin.
version: 0.0.1
author: Stefan Wehr (wehr@cp-med.com)
homepage: https://github.com/factisresearch/sum_data_types

environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: none
dependencies:
  analyzer: ^1.1.0
  pedantic: ^1.8.0
  build: ^2.0.0
  # sum_data_types: ^0.0.1
  sum_data_types:
    git:
      url: https://github.com/factisresearch/sum_data_types
      path: sum_data_types
      ref: 90e9646586490f61f0b917930f34261ea2006675
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^1.11.5
