#!/bin/bash

HERE=$(cd $(dirname ${BASH_SOURCE[0]}) > /dev/null && pwd -P)
cd $HERE/..

set -o errexit
set -o pipefail
set -o nounset

if [ "${1-}" == "--prepare" ]; then
   echo
   echo "Preparing ..."
   scripts/prepare || exit 1
   echo "Done preparing"
fi
echo
echo "Checking code format ..."
scripts/check-format || exit 1
echo "Done checking code format"
echo
echo "Running analyzer checks ..."
scripts/check-analyzer || exit 1
echo "Done with analyzer checks"
echo
echo "Running tests ..."
scripts/run-tests
echo "Done with tests"
echo
echo "All good :-)"
