#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

HERE=$(cd $(dirname ${BASH_SOURCE[0]}) > /dev/null && pwd -P)
cd $HERE/..

for d in . sum_data_types_generator example; do
    (
        cd "$d"
        echo
        echo -n "==> Running 'dart analyze' in "
        pwd
        if [ "$d" == "example" ]; then
            dart run build_runner build --delete-conflicting-outputs
            dart analyze --fatal-infos --fatal-warnings test
        else
            dart analyze --fatal-infos --fatal-warnings lib
        fi
    )
done
