#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

HERE=$(cd $(dirname ${BASH_SOURCE[0]}) > /dev/null && pwd -P)
cd $HERE

echo
echo "==> Checking code formatting..."
if ./format --check; then
    code=$?
    echo No issues found!
else
    code=$?
fi
exit $code
