#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

HERE=$(cd $(dirname ${BASH_SOURCE[0]}) > /dev/null && pwd -P)
cd $HERE/..

if [ "${1-}" == "--prepare" ]; then
   scripts/prepare
fi

scripts/check-format
scripts/check-analyzer
scripts/run-tests --skip-codegen

echo
echo "All good :-)"
