#!/bin/bash

HERE=$(cd $(dirname ${BASH_SOURCE[0]}) > /dev/null && pwd -P)
cd $HERE/..

set -o errexit
set -o pipefail
set -o nounset

ok=yes

echo "Checking if code formatting is ok ..."

IFS='
'
for x in `scripts/format --check`; do
    ok=no
    echo "Error: $x"
done

if [ "$ok" == "yes" ]; then
    echo "Code formatting is ok."
    exit 0
elif [ "$ok" == "no" ]; then
    echo "Detected code formatting errors!"
    exit 1
fi
