#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

HERE=$(cd $(dirname ${BASH_SOURCE[0]}) > /dev/null && pwd -P)
cd $HERE/..

usage()
{
    echo "$0 [--check]"
    exit 1
}

opts=()
if [ "${1-}" == "--help" ]; then
    usage
elif [ "${1-}" == "--check" ]; then
    opts+=("--set-exit-if-changed" "--output" "none")
elif [ ! -z "${1-}" ]; then
    usage
fi

find lib sum_data_types_generator/lib example/lib -name '*.dart' -not -name '*.g.dart' | xargs dart format ${opts[*]} --line-length 100
