#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

HERE=$(cd $(dirname ${BASH_SOURCE[0]}) > /dev/null && pwd -P)
cd $HERE/..

for d in . sum_data_types_generator example; do
    (
        cd "$d"
        echo
        echo -n "==> from "
        pwd
        dart pub get
    )
done
