#!/bin/bash

HERE=$(cd $(dirname ${BASH_SOURCE[0]}) > /dev/null && pwd -P)
cd $HERE/..

set -o errexit
set -o pipefail
set -o nounset

if [ "${1-}" == "-h" -o "${1-}" == "--help" ]; then
    echo "USAGE: $0 [--skip-codegen]"
    exit 0
fi

pushd example > /dev/null

if [ "${1-}" != "--skip-codegen" ]; then
    pub run build_runner build || exit 1
fi

pub run test lib/data_classes.dart lib/sum_types.dart || exit 1
